"""Run the Jump Probability Cup forecasting pipeline from CSV.

Usage:
    python src/pipeline.py --input data/turkey_paraguay_model_input.csv --output data/turkey_paraguay_final_v3.csv
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, Optional

from calibration import final_probability, red_team_flags
from model_engine import compute_model_probability
from schema import REQUIRED_COLUMNS


def parse_optional_float(value: str) -> Optional[float]:
    value = (value or "").strip()
    if value == "":
        return None
    x = float(value)
    if x > 1.0:
        x = x / 100.0
    if not 0.0 <= x <= 1.0:
        raise ValueError(f"probability out of range: {value}")
    return x


def parse_float(value: str, default: float = 0.0) -> float:
    value = (value or "").strip()
    if value == "":
        return default
    x = float(value)
    if abs(x) > 1.0 and default != 0.0:
        x = x / 100.0
    return x


def validate_headers(headers: list[str]) -> None:
    missing = [c for c in REQUIRED_COLUMNS if c not in headers]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def process_row(row: Dict[str, str], winner_mode: bool = True) -> Dict[str, str]:
    market_type = row["market_type"].strip()
    base_prob = parse_optional_float(row["base_prob"])
    if base_prob is None:
        raise ValueError(f"base_prob missing for {row.get('question_id')}")
    market_prob = parse_optional_float(row.get("market_prob", ""))

    # If model_family is present, model_prob is generated by the statistical model.
    generated_model_prob = compute_model_probability(row)
    manual_model_prob = parse_optional_float(row.get("model_prob", ""))
    model_prob = generated_model_prob if generated_model_prob is not None else manual_model_prob

    context_adj = parse_float(row.get("context_adj", "0"), default=0.0)
    if abs(context_adj) > 1:
        context_adj = context_adj / 100.0
    confidence = row.get("confidence", "medium").strip() or "medium"
    expected_field_prob = parse_optional_float(row.get("expected_field_prob", ""))
    evidence_score = parse_optional_float(row.get("evidence_score", ""))

    raw, anchor, coeff, shrunk, final = final_probability(
        market_type=market_type,
        base_prob=base_prob,
        market_prob=market_prob,
        model_prob=model_prob,
        context_adj=context_adj,
        confidence=confidence,
        evidence_score=evidence_score,
        winner_mode=winner_mode,
    )
    flags = red_team_flags(market_type, final, expected_field_prob, evidence_score, model_prob, market_prob)
    edge_vs_field = "" if expected_field_prob is None else f"{(final - expected_field_prob) * 100:.1f}pp"

    out = dict(row)
    out.update(
        {
            "generated_model_probability": "" if generated_model_prob is None else f"{generated_model_prob:.4f}",
            "used_model_probability": "" if model_prob is None else f"{model_prob:.4f}",
            "anchor_probability": f"{anchor:.4f}",
            "shrink_coeff": f"{coeff:.2f}",
            "raw_probability": f"{raw:.4f}",
            "shrunk_probability": f"{shrunk:.4f}",
            "final_probability": f"{final:.4f}",
            "submit_probability_0_100": str(round(final * 100)),
            "edge_vs_expected_field": edge_vs_field,
            "red_team_flags": " | ".join(flags),
            "update_triggers": "lineups; injuries/suspensions; referee; weather; tactical news; market move",
        }
    )
    return out


def run(input_path: Path, output_path: Path, winner_mode: bool = True) -> None:
    with input_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        validate_headers(reader.fieldnames or [])
        rows = [process_row(row, winner_mode=winner_mode) for row in reader]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    extra_cols = [
        "generated_model_probability",
        "used_model_probability",
        "anchor_probability",
        "shrink_coeff",
        "raw_probability",
        "shrunk_probability",
        "final_probability",
        "submit_probability_0_100",
        "edge_vs_expected_field",
        "red_team_flags",
        "update_triggers",
    ]
    fieldnames = list(reader.fieldnames or []) + [c for c in extra_cols if c not in (reader.fieldnames or [])]
    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--safe-mode", action="store_true", help="Use normal caps; default is winner mode.")
    args = parser.parse_args()
    run(args.input, args.output, winner_mode=not args.safe_mode)
